### ISSUE TITLE
disable that create account link

### ISSUE THREAD

**Issue by connieimdialog** [globalvoices/NewsFrames-Code#1]
let's go ahead and do this now until we come up with a more concrete account strategy

**Comment by sapraaman** [comment]
Pull request submitted @scttnlsn

**Comment by shrutimehta13** [comment]
No Signup option in UI
url/users/register prompts restricted area. 
note- tested on stage, new signup works after entering restricted page with credentials

**Comment by CrisNelson** [comment]
@connieimdialog - this is fixed on staging. With approval we can push to prod (right @sapraaman ?)
