### ISSUE TITLE
Question-Media Cloud word image workflow after image is dropped to etherpad

### ISSUE THREAD

**Issue by shrutimehta13** [globalvoices/NewsFrames-Code#10]
We can choose 'Add to Pad' option to insert Media Cloud Word Image to etherpad.
Need workflow inputs please how the users will use it after this step.

I had few observations, not sure if these are issues. 
1. Choose Export button from the toolbar, image scale and appear blurred in the html
2. Choose Import/Export button, Export current pad as say html- Media cloud word images do not appear. 
<img width="1387" alt="screen shot 2018-05-05 at 6 46 49 pm" src="https://user-images.githubusercontent.com/34771314/39663659-e4511d9c-5094-11e8-998d-1fc396e72a14.png">

**Comment by connieimdialog** [comment]
hi @shrutimehta13 
for #1 the resolution of the png should be increased. ty, i will create a ticket.
#2 yes this should appear in the HTML code, can you create this ticket as a bug?

**Comment by sapraaman** [comment]
@connieimdialog did you create tickets for above issues ? cc @CrisNelson
