### ISSUE TITLE
Cannot add MC image to pad when the tool section is widest

### ISSUE THREAD

**Issue by connieimdialog** [globalvoices/NewsFrames-Code#11]
Hi, 
for example, in this project: http://gv-stage.dev.colab.coop/projects/32

if you expand the tool panel all the way out like the screenshot, doesn't seem as if you can add to pad.
<img width="1269" alt="screen shot 2018-05-08 at 9 26 27 am" src="https://user-images.githubusercontent.com/5280556/39746350-f94324fc-52a1-11e8-8b06-e4ba868302d7.png">

is this just me?

**Comment by shrutimehta13** [comment]
Yes cannot add to Pad when sidebar is fully expanded.
also, Image cloud appears with ellipses when toggled to half. When expanded to full, the word cloud appears with more text and does not work.

**Comment by connieimdialog** [comment]
if #12 is possible then we don't need this one as critically

**Comment by sapraaman** [comment]
Pull request submitted for review @scttnlsn

**Comment by sapraaman** [comment]
This has been fixed now

**Comment by connieimdialog** [comment]
looks good on my end!
