### ISSUE TITLE
Increased MC frequency word count needed for mid-size panel

### ISSUE THREAD

**Issue by connieimdialog** [globalvoices/NewsFrames-Code#12]
hi,
i think this was working before but didn't catch this with the panel updates.  can we change the mid-size view to contain the set of more words (rather than the same as the reduced view)? in other words, possible to use the same number of words used in the full tool panel ?

assuming this isn't a huge amount of work, so can go ahead and do it.

see the attachments for 1) narrow panel, 2) mid-size, 3) full
1)
<img width="1264" alt="screen shot 2018-05-08 at 9 30 02 am" src="https://user-images.githubusercontent.com/5280556/39746536-7e287f6e-52a2-11e8-86fa-4d83d86c1e24.png">

2) 
<img width="1248" alt="screen shot 2018-05-08 at 9 30 11 am" src="https://user-images.githubusercontent.com/5280556/39746547-882edcce-52a2-11e8-8ed1-152638967f14.png">

3) 
<img width="1269" alt="screen shot 2018-05-08 at 9 26 27 am" src="https://user-images.githubusercontent.com/5280556/39746559-92b87024-52a2-11e8-9cd6-6e9a3b6f3137.png">

**Comment by connieimdialog** [comment]
side note, i would say that given #11 will not be easily resolved, this is high priority and can just be done.   cc @CrisNelson @scttnlsn

**Comment by CrisNelson** [comment]
On staging and ready for testing @shrutimehta13

**Comment by shrutimehta13** [comment]
tested mid size panel word count. It now shows word count same as full size panel display instead of narrow panel word count.
note- tested with saved mc searches. unable to create new mc search- error Media Cloud not responding
