### ISSUE TITLE
Gemfile warning

### ISSUE THREAD

**Issue by connieimdialog** [globalvoices/NewsFrames-Code#15]
hey @scttnlsn did this get resolved? i cannot remember, but i also continue to see the alert, so just flaggin....

**Comment by scttnlsn** [comment]
Hi @connieimdialog, this was fixed on the `develop` branch so I believe that warning will continue to be displayed until `develop` is merged into `master`.

**Comment by CrisNelson** [comment]
@shrutimehta13 - Just a general test on staging for basic functionality to make sure updating gems didn't break anything.
