### ISSUE TITLE
Cannot download Media Cloud Saved Searches .csvs

### ISSUE THREAD

**Issue by connieimdialog** [globalvoices/NewsFrames-Code#25]
Hi, something appears to have broken, not sure when but it is both on staging and on production. If you select any saved search and try to download a story or a frequency CSV, it says "something is wrong"

**Comment by connieimdialog** [comment]
note that Media Cloud has been going up and down - apparently they have hardware server issues (something is to be replaced by end of week). so may be related. but if that's the case, then wondering if there's a more elegant solution/error message ("Media Cloud not responding")

**Comment by scttnlsn** [comment]
@connieimdialog Seems we're getting a lot of errors from the MediaCloud API at the moment- I also can't make any sort of query.

```
Error(s): Caught exception in MediaWords::Controller::Api::V2::Stories_Public->count Error fetching Solr response: Solr error: undefined field sentence
```

We could certainly show a better error message here- I'll submit a PR for that.

**Comment by scttnlsn** [comment]
PR opened: https://github.com/globalvoices/NewsFrames-Code/pull/26

**Comment by CrisNelson** [comment]
Hard to test as we need MC to not function in order to see the new error message. OK to push with the next release.

**Comment by shrutimehta13** [comment]
MC Save Search showing error- Media Cloud not responding.

MC Download csv shows error most of the time (tried multiple times around 8:30pm IST)
 We're sorry, but something went wrong.
If you are the application owner check the logs for more information.
<img width="820" alt="screen shot 2018-06-15 at 8 26 26 pm" src="https://user-images.githubusercontent.com/34771314/41475246-dfe311f4-70db-11e8-8965-0cefae1dcac5.png">


@scttnlsn strange behaviour
please check this http://gv-stage.dev.colab.coop/projects/78# . Here first saved search by the name 'google assistant' works but none of the others. so is this search specific not a communication problem with mc?

**Comment by CrisNelson** [comment]
This last test was not using the story based searching.

**Comment by CrisNelson** [comment]
@connieimdialog @scttnlsn - does anything need to be done here? We have to wait for MC to go down to check the error messaging, yes?

**Comment by connieimdialog** [comment]
looks good
