### ISSUE TITLE
MC: story based searching

### ISSUE THREAD

**Issue by CrisNelson** [globalvoices/NewsFrames-Code#31]
https://mediacloud.org/news/2018/4/12/switching-to-story-based-searching-on-may-12th

**Comment by connieimdialog** [comment]
i am hoping it's not huge, in which case, just do it! :)

**Comment by scttnlsn** [comment]
This was a simple change.  PR opened here: https://github.com/globalvoices/NewsFrames-Code/pull/32

**Comment by CrisNelson** [comment]
Test w/ various types MC queries

**Comment by connieimdialog** [comment]
@scttnlsn 
1) if i type a word into the box, the search doesn't work (think needs to be updated to story level search)
2) i can't seem to click on 'saved searches' here: http://gv-stage.dev.colab.coop/projects/12

**Comment by scttnlsn** [comment]
@connieimdialog What word are you entering?  I cannot reproduce.  Fix for item 2 is here: https://github.com/globalvoices/NewsFrames-Code/pull/35

**Comment by scttnlsn** [comment]
FYI- item 2 is not related to story-based searching but rather https://github.com/globalvoices/NewsFrames-Code/issues/28

**Comment by CrisNelson** [comment]
@scttnlsn @connieimdialog - checking on this one. Sounds like we can't reproduce item 1 and item 2 was fixed in another ticket. Can we close this one?
