### ISSUE TITLE
Production- Etherpad not loading

### ISSUE THREAD

**Issue by shrutimehta13** [globalvoices/NewsFrames-Code#36]
https://www.newsframes.org/

Steps:
Create a new project/ select a Project to edit

observed- ether pad not loading
Failed to load resource: the server responded with a status of 500 (Internal Server Error)  https://www.newsframes.org/projects/81/pads?_=1530690713295

Note- yesterday, ether pad was loading, but MC Add to pad was not working

**Comment by CrisNelson** [comment]
This is fixed, yes @sapraaman ?

**Comment by shrutimehta13** [comment]
Tested on production- fixed

**Comment by shrutimehta13** [comment]
@sapraaman for analysis regarding ether pad settings and how these got modified on prod, i think we should raise another ticket.
