### ISSUE TITLE
Gemfile.lock update suggested: sprockets ~> 3.7.2.

### ISSUE THREAD

**Issue by CrisNelson** [globalvoices/NewsFrames-Code#37]
Known high severity security vulnerability detected in sprockets >=3.0.0,<3.7.2defined in Gemfile.lock.Gemfile.lock update suggested: sprockets ~> 3.7.2. | Known high severity security vulnerability detected in sprockets >=3.0.0,<3.7.2defined in Gemfile.lock. | Gemfile.lock update suggested: sprockets ~> 3.7.2.
Known high severity security vulnerability detected in sprockets >=3.0.0,<3.7.2defined in Gemfile.lock.
Gemfile.lock update suggested: sprockets ~> 3.7.2.

https://github.com/globalvoices/NewsFrames-Code/network/dependencies

**Comment by scttnlsn** [comment]
@sapraaman I updated Sprockets on `develop`.  Since we have not committed anything else to `master` since the last deploy I think it also makes sense to merge into `master` and do a production deploy.  What do you think?

**Comment by sapraaman** [comment]
Agreed @scttnlsn , do you want to do it, or you doing it ?

**Comment by scttnlsn** [comment]
@sapraaman Yeah, I can do it
