### ISSUE TITLE
Chrome: Adding MC word image takes time (range 6-12sec), related issue of null image

### ISSUE THREAD

**Issue by shrutimehta13** [globalvoices/NewsFrames-Code#7]
MC word Image 'Add to Pad' on Chrome , takes time to add. No clue to user if the operation is in progress or failed. During this transaction time, if user switches search (New or Saved) or switches to any other feature then a null image gets added
<img width="350" alt="screen shot 2018-05-04 at 5 46 46 pm" src="https://user-images.githubusercontent.com/34771314/39627413-74af4fa8-4fc3-11e8-8d3e-fb357b878c1c.png">

Works fine on Firefox- Image is immediately added

**Comment by connieimdialog** [comment]
estimate pls, ty @sapraaman

**Comment by sapraaman** [comment]
@connieimdialog is that an ok resolution to display a progress bar saying something like "Adding media cloud image..."

**Comment by sapraaman** [comment]
Pull request submitted for review @scttnlsn

**Comment by sapraaman** [comment]
Display a progress bar when browser is taking time to generate image for the first time

**Comment by shrutimehta13** [comment]
@connieimdialog  note- progress bar is displayed for action 'in progress' cue to User. 
But user can still click anywhere else (same problem).
If context is changed, null image gets added
If user starts typing elsewhere, image gets added as per the current cursor position
