### ISSUE TITLE
MC word Image- No author details shown 

### ISSUE THREAD

**Issue by shrutimehta13** [globalvoices/NewsFrames-Code#9]
<img width="546" alt="mc image author" src="https://user-images.githubusercontent.com/34771314/39628892-19c450f2-4fc8-11e8-91a4-9231756df902.png">
Add a Media Cloud Word Image to a Pad
Here no Author details are shown as to who added this word image.

Shouldn't it be shown?

**Comment by connieimdialog** [comment]
thanks for the eagle eye @shrutimehta13 ! i think this is ok not to show for now
